//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("patient_info_dbModel", "fk_emergency_contact_Patient", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.patient), "emergency_contact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.emergency_contact), true)]

#endregion

namespace DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class patient_info_dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new patient_info_dbEntities object using the connection string found in the 'patient_info_dbEntities' section of the application configuration file.
        /// </summary>
        public patient_info_dbEntities() : base("name=patient_info_dbEntities", "patient_info_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new patient_info_dbEntities object.
        /// </summary>
        public patient_info_dbEntities(string connectionString) : base(connectionString, "patient_info_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new patient_info_dbEntities object.
        /// </summary>
        public patient_info_dbEntities(EntityConnection connection) : base(connection, "patient_info_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<emergency_contact> emergency_contact
        {
            get
            {
                if ((_emergency_contact == null))
                {
                    _emergency_contact = base.CreateObjectSet<emergency_contact>("emergency_contact");
                }
                return _emergency_contact;
            }
        }
        private ObjectSet<emergency_contact> _emergency_contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<patient> patient
        {
            get
            {
                if ((_patient == null))
                {
                    _patient = base.CreateObjectSet<patient>("patient");
                }
                return _patient;
            }
        }
        private ObjectSet<patient> _patient;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the emergency_contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemergency_contact(emergency_contact emergency_contact)
        {
            base.AddObject("emergency_contact", emergency_contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the patient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopatient(patient patient)
        {
            base.AddObject("patient", patient);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="surname">No Metadata Documentation available.</param>
        /// <param name="phone">No Metadata Documentation available.</param>
        /// <param name="idPatient">No Metadata Documentation available.</param>
        public int insertEmergencyContact(ObjectParameter id, global::System.String name, global::System.String surname, global::System.String phone, Nullable<global::System.Int64> idPatient)
        {
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("name", typeof(global::System.String));
            }
    
            ObjectParameter surnameParameter;
            if (surname != null)
            {
                surnameParameter = new ObjectParameter("surname", surname);
            }
            else
            {
                surnameParameter = new ObjectParameter("surname", typeof(global::System.String));
            }
    
            ObjectParameter phoneParameter;
            if (phone != null)
            {
                phoneParameter = new ObjectParameter("phone", phone);
            }
            else
            {
                phoneParameter = new ObjectParameter("phone", typeof(global::System.String));
            }
    
            ObjectParameter idPatientParameter;
            if (idPatient.HasValue)
            {
                idPatientParameter = new ObjectParameter("idPatient", idPatient);
            }
            else
            {
                idPatientParameter = new ObjectParameter("idPatient", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction("insertEmergencyContact", id, nameParameter, surnameParameter, phoneParameter, idPatientParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="id">No Metadata Documentation available.</param>
        /// <param name="idInDev">No Metadata Documentation available.</param>
        /// <param name="name">No Metadata Documentation available.</param>
        /// <param name="surname">No Metadata Documentation available.</param>
        /// <param name="addr">No Metadata Documentation available.</param>
        /// <param name="dni">No Metadata Documentation available.</param>
        /// <param name="birth">No Metadata Documentation available.</param>
        /// <param name="sex">No Metadata Documentation available.</param>
        /// <param name="neighbour">No Metadata Documentation available.</param>
        /// <param name="city">No Metadata Documentation available.</param>
        /// <param name="phone">No Metadata Documentation available.</param>
        /// <param name="cell">No Metadata Documentation available.</param>
        /// <param name="email">No Metadata Documentation available.</param>
        /// <param name="register_number">No Metadata Documentation available.</param>
        public int insertPatient(ObjectParameter id, Nullable<global::System.Int64> idInDev, global::System.String name, global::System.String surname, global::System.String addr, global::System.String dni, Nullable<global::System.DateTime> birth, global::System.String sex, global::System.String neighbour, global::System.String city, global::System.String phone, global::System.String cell, global::System.String email, Nullable<global::System.Int64> register_number)
        {
            ObjectParameter idInDevParameter;
            if (idInDev.HasValue)
            {
                idInDevParameter = new ObjectParameter("idInDev", idInDev);
            }
            else
            {
                idInDevParameter = new ObjectParameter("idInDev", typeof(global::System.Int64));
            }
    
            ObjectParameter nameParameter;
            if (name != null)
            {
                nameParameter = new ObjectParameter("name", name);
            }
            else
            {
                nameParameter = new ObjectParameter("name", typeof(global::System.String));
            }
    
            ObjectParameter surnameParameter;
            if (surname != null)
            {
                surnameParameter = new ObjectParameter("surname", surname);
            }
            else
            {
                surnameParameter = new ObjectParameter("surname", typeof(global::System.String));
            }
    
            ObjectParameter addrParameter;
            if (addr != null)
            {
                addrParameter = new ObjectParameter("addr", addr);
            }
            else
            {
                addrParameter = new ObjectParameter("addr", typeof(global::System.String));
            }
    
            ObjectParameter dniParameter;
            if (dni != null)
            {
                dniParameter = new ObjectParameter("dni", dni);
            }
            else
            {
                dniParameter = new ObjectParameter("dni", typeof(global::System.String));
            }
    
            ObjectParameter birthParameter;
            if (birth.HasValue)
            {
                birthParameter = new ObjectParameter("birth", birth);
            }
            else
            {
                birthParameter = new ObjectParameter("birth", typeof(global::System.DateTime));
            }
    
            ObjectParameter sexParameter;
            if (sex != null)
            {
                sexParameter = new ObjectParameter("sex", sex);
            }
            else
            {
                sexParameter = new ObjectParameter("sex", typeof(global::System.String));
            }
    
            ObjectParameter neighbourParameter;
            if (neighbour != null)
            {
                neighbourParameter = new ObjectParameter("neighbour", neighbour);
            }
            else
            {
                neighbourParameter = new ObjectParameter("neighbour", typeof(global::System.String));
            }
    
            ObjectParameter cityParameter;
            if (city != null)
            {
                cityParameter = new ObjectParameter("city", city);
            }
            else
            {
                cityParameter = new ObjectParameter("city", typeof(global::System.String));
            }
    
            ObjectParameter phoneParameter;
            if (phone != null)
            {
                phoneParameter = new ObjectParameter("phone", phone);
            }
            else
            {
                phoneParameter = new ObjectParameter("phone", typeof(global::System.String));
            }
    
            ObjectParameter cellParameter;
            if (cell != null)
            {
                cellParameter = new ObjectParameter("cell", cell);
            }
            else
            {
                cellParameter = new ObjectParameter("cell", typeof(global::System.String));
            }
    
            ObjectParameter emailParameter;
            if (email != null)
            {
                emailParameter = new ObjectParameter("email", email);
            }
            else
            {
                emailParameter = new ObjectParameter("email", typeof(global::System.String));
            }
    
            ObjectParameter register_numberParameter;
            if (register_number.HasValue)
            {
                register_numberParameter = new ObjectParameter("register_number", register_number);
            }
            else
            {
                register_numberParameter = new ObjectParameter("register_number", typeof(global::System.Int64));
            }
    
            return base.ExecuteFunction("insertPatient", id, idInDevParameter, nameParameter, surnameParameter, addrParameter, dniParameter, birthParameter, sexParameter, neighbourParameter, cityParameter, phoneParameter, cellParameter, emailParameter, register_numberParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="patient_info_dbModel", Name="emergency_contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class emergency_contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new emergency_contact object.
        /// </summary>
        /// <param name="idemergency_contact">Initial value of the idemergency_contact property.</param>
        /// <param name="patient_idPatient">Initial value of the patient_idPatient property.</param>
        public static emergency_contact Createemergency_contact(global::System.Int64 idemergency_contact, global::System.Int64 patient_idPatient)
        {
            emergency_contact emergency_contact = new emergency_contact();
            emergency_contact.idemergency_contact = idemergency_contact;
            emergency_contact.patient_idPatient = patient_idPatient;
            return emergency_contact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idemergency_contact
        {
            get
            {
                return _idemergency_contact;
            }
            set
            {
                if (_idemergency_contact != value)
                {
                    Onidemergency_contactChanging(value);
                    ReportPropertyChanging("idemergency_contact");
                    _idemergency_contact = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idemergency_contact");
                    Onidemergency_contactChanged();
                }
            }
        }
        private global::System.Int64 _idemergency_contact;
        partial void Onidemergency_contactChanging(global::System.Int64 value);
        partial void Onidemergency_contactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 patient_idPatient
        {
            get
            {
                return _patient_idPatient;
            }
            set
            {
                Onpatient_idPatientChanging(value);
                ReportPropertyChanging("patient_idPatient");
                _patient_idPatient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("patient_idPatient");
                Onpatient_idPatientChanged();
            }
        }
        private global::System.Int64 _patient_idPatient;
        partial void Onpatient_idPatientChanging(global::System.Int64 value);
        partial void Onpatient_idPatientChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("patient_info_dbModel", "fk_emergency_contact_Patient", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="patient_info_dbModel", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new patient object.
        /// </summary>
        /// <param name="idPatient">Initial value of the idPatient property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="surname">Initial value of the surname property.</param>
        /// <param name="document">Initial value of the document property.</param>
        /// <param name="gender">Initial value of the gender property.</param>
        public static patient Createpatient(global::System.Int64 idPatient, global::System.String name, global::System.String surname, global::System.String document, global::System.String gender)
        {
            patient patient = new patient();
            patient.idPatient = idPatient;
            patient.name = name;
            patient.surname = surname;
            patient.document = document;
            patient.gender = gender;
            return patient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idPatient
        {
            get
            {
                return _idPatient;
            }
            set
            {
                if (_idPatient != value)
                {
                    OnidPatientChanging(value);
                    ReportPropertyChanging("idPatient");
                    _idPatient = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPatient");
                    OnidPatientChanged();
                }
            }
        }
        private global::System.Int64 _idPatient;
        partial void OnidPatientChanging(global::System.Int64 value);
        partial void OnidPatientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String patientReference
        {
            get
            {
                return _patientReference;
            }
            set
            {
                OnpatientReferenceChanging(value);
                ReportPropertyChanging("patientReference");
                _patientReference = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("patientReference");
                OnpatientReferenceChanged();
            }
        }
        private global::System.String _patientReference;
        partial void OnpatientReferenceChanging(global::System.String value);
        partial void OnpatientReferenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String document
        {
            get
            {
                return _document;
            }
            set
            {
                OndocumentChanging(value);
                ReportPropertyChanging("document");
                _document = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("document");
                OndocumentChanged();
            }
        }
        private global::System.String _document;
        partial void OndocumentChanging(global::System.String value);
        partial void OndocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cell_phone
        {
            get
            {
                return _cell_phone;
            }
            set
            {
                Oncell_phoneChanging(value);
                ReportPropertyChanging("cell_phone");
                _cell_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cell_phone");
                Oncell_phoneChanged();
            }
        }
        private global::System.String _cell_phone;
        partial void Oncell_phoneChanging(global::System.String value);
        partial void Oncell_phoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String neighborhood
        {
            get
            {
                return _neighborhood;
            }
            set
            {
                OnneighborhoodChanging(value);
                ReportPropertyChanging("neighborhood");
                _neighborhood = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("neighborhood");
                OnneighborhoodChanged();
            }
        }
        private global::System.String _neighborhood;
        partial void OnneighborhoodChanging(global::System.String value);
        partial void OnneighborhoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> birthday
        {
            get
            {
                return _birthday;
            }
            set
            {
                OnbirthdayChanging(value);
                ReportPropertyChanging("birthday");
                _birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birthday");
                OnbirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _birthday;
        partial void OnbirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnbirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String e_mail
        {
            get
            {
                return _e_mail;
            }
            set
            {
                One_mailChanging(value);
                ReportPropertyChanging("e_mail");
                _e_mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("e_mail");
                One_mailChanged();
            }
        }
        private global::System.String _e_mail;
        partial void One_mailChanging(global::System.String value);
        partial void One_mailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> register_number
        {
            get
            {
                return _register_number;
            }
            set
            {
                Onregister_numberChanging(value);
                ReportPropertyChanging("register_number");
                _register_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("register_number");
                Onregister_numberChanged();
            }
        }
        private Nullable<global::System.Int64> _register_number;
        partial void Onregister_numberChanging(Nullable<global::System.Int64> value);
        partial void Onregister_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> modified_date
        {
            get
            {
                return _modified_date;
            }
            set
            {
                Onmodified_dateChanging(value);
                ReportPropertyChanging("modified_date");
                _modified_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("modified_date");
                Onmodified_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _modified_date;
        partial void Onmodified_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onmodified_dateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("patient_info_dbModel", "fk_emergency_contact_Patient", "emergency_contact")]
        public EntityCollection<emergency_contact> emergency_contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<emergency_contact>("patient_info_dbModel.fk_emergency_contact_Patient", "emergency_contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<emergency_contact>("patient_info_dbModel.fk_emergency_contact_Patient", "emergency_contact", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
