//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace IntegrationHC.DatosPacienteRegistro {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSrvDarColPer1SoapBinding", Namespace="kb3")]
    public partial class WebSrvDarColPer1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebSrvDarColPer1() {
            this.Url = global::IntegrationHC.Properties.Settings.Default.IntegrationHC_DatosPacienteRegistro_WebSrvDarColPer1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("kb3action/AWEBSRVDARCOLPER1.Execute", RequestElementName="WebSrvDarColPer1.Execute", RequestNamespace="kb3", ResponseElementName="WebSrvDarColPer1.ExecuteResponse", ResponseNamespace="kb3", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Execute([System.Xml.Serialization.XmlArrayItemAttribute(Namespace="kb2", IsNullable=false)] ref DatPersona_2DatPersona_2Item[] Persona, [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="kb2", IsNullable=false)] ref RegistrosBuscadosRegistrosBuscadosItem[] Listaregistros) {
            object[] results = this.Invoke("Execute", new object[] {
                        Persona,
                        Listaregistros});
            Persona = ((DatPersona_2DatPersona_2Item[])(results[0]));
            Listaregistros = ((RegistrosBuscadosRegistrosBuscadosItem[])(results[1]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(DatPersona_2DatPersona_2Item[] Persona, RegistrosBuscadosRegistrosBuscadosItem[] Listaregistros) {
            this.ExecuteAsync(Persona, Listaregistros, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(DatPersona_2DatPersona_2Item[] Persona, RegistrosBuscadosRegistrosBuscadosItem[] Listaregistros, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Persona,
                        Listaregistros}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DatPersona_2.DatPersona_2Item", Namespace="kb2")]
    public partial class DatPersona_2DatPersona_2Item {

        private string datPersonaCedNum2Field;

        private string datPersonaVerNum2Field;

        private string datPersonaRazCod2Field;
        
        private string datPersonaNombres2Field;
        
        private string datPersonaApellidos2Field;

        private string datPersonaFchNac2Field;
        
        private string datPersonaSexo2Field;
        
        private string datPersonaRaza2Field;
        
        private string datPersonaNacion2Field;
        
        private string datPersonaCredNum2Field;

        private string datPersonaFchFac2Field;

        private string datPersonaEdad2Field;

        private string datPersonaUltCarnet2Field;
        
        private string datPersonaUltDomicilio2Field;
        
        private string datPersonaUltTelefono2Field;
        
        private string datPersonaApeCony2Field;

        private string datPersonaRegNum2Field;

        private string datPersonaPacCarNumField;
        
        private string datPersonaPacDonField;

        private string datPersonaCantDonField;
        
        private string datPersonaAutorizadoField;
        
        /// <remarks/>
        public string DatPersonaCedNum2
        {
            get {
                return this.datPersonaCedNum2Field;
            }
            set {
                this.datPersonaCedNum2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaVerNum2
        {
            get {
                return this.datPersonaVerNum2Field;
            }
            set {
                this.datPersonaVerNum2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaRazCod2
        {
            get {
                return this.datPersonaRazCod2Field;
            }
            set {
                this.datPersonaRazCod2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaNombres2 {
            get {
                return this.datPersonaNombres2Field;
            }
            set {
                this.datPersonaNombres2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaApellidos2 {
            get {
                return this.datPersonaApellidos2Field;
            }
            set {
                this.datPersonaApellidos2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaFchNac2
        {
            get {
                return this.datPersonaFchNac2Field;
            }
            set {
                this.datPersonaFchNac2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaSexo2 {
            get {
                return this.datPersonaSexo2Field;
            }
            set {
                this.datPersonaSexo2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaRaza2 {
            get {
                return this.datPersonaRaza2Field;
            }
            set {
                this.datPersonaRaza2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaNacion2 {
            get {
                return this.datPersonaNacion2Field;
            }
            set {
                this.datPersonaNacion2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaCredNum2 {
            get {
                return this.datPersonaCredNum2Field;
            }
            set {
                this.datPersonaCredNum2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaFchFac2
        {
            get {
                return this.datPersonaFchFac2Field;
            }
            set {
                this.datPersonaFchFac2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaEdad2
        {
            get {
                return this.datPersonaEdad2Field;
            }
            set {
                this.datPersonaEdad2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaUltCarnet2
        {
            get {
                return this.datPersonaUltCarnet2Field;
            }
            set {
                this.datPersonaUltCarnet2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaUltDomicilio2 {
            get {
                return this.datPersonaUltDomicilio2Field;
            }
            set {
                this.datPersonaUltDomicilio2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaUltTelefono2 {
            get {
                return this.datPersonaUltTelefono2Field;
            }
            set {
                this.datPersonaUltTelefono2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaApeCony2 {
            get {
                return this.datPersonaApeCony2Field;
            }
            set {
                this.datPersonaApeCony2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaRegNum2
        {
            get {
                return this.datPersonaRegNum2Field;
            }
            set {
                this.datPersonaRegNum2Field = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaPacCarNum
        {
            get {
                return this.datPersonaPacCarNumField;
            }
            set {
                this.datPersonaPacCarNumField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaPacDon {
            get {
                return this.datPersonaPacDonField;
            }
            set {
                this.datPersonaPacDonField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaCantDon
        {
            get {
                return this.datPersonaCantDonField;
            }
            set {
                this.datPersonaCantDonField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaAutorizado {
            get {
                return this.datPersonaAutorizadoField;
            }
            set {
                this.datPersonaAutorizadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="RegistrosBuscados.RegistrosBuscadosItem", Namespace="kb2")]
    public partial class RegistrosBuscadosRegistrosBuscadosItem {
        
        private int numeroRegistroBuscadoField;
        
        /// <remarks/>
        public int NumeroRegistroBuscado {
            get {
                return this.numeroRegistroBuscadoField;
            }
            set {
                this.numeroRegistroBuscadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatPersona_2DatPersona_2Item[] Persona {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatPersona_2DatPersona_2Item[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public RegistrosBuscadosRegistrosBuscadosItem[] Listaregistros {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RegistrosBuscadosRegistrosBuscadosItem[])(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591