//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18052.
// 
#pragma warning disable 1591

namespace IntegrationHC.DatosPacienteCI {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebSrvDatosPersonaCdaSoapBinding", Namespace="kb2")]
    public partial class WebSrvDatosPersonaCda : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ExecuteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebSrvDatosPersonaCda() {
            this.Url = global::IntegrationHC.Properties.Settings.Default.IntegrationHC_DatosPacienteCI_2_WebSrvDatosPersonaCda;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ExecuteCompletedEventHandler ExecuteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("kb2action/AWEBSRVDATOSPERSONACDA.Execute", RequestElementName="WebSrvDatosPersonaCda.Execute", RequestNamespace="kb2", ResponseElementName="WebSrvDatosPersonaCda.ExecuteResponse", ResponseNamespace="kb2", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Execute([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref DatPersonaCdaDatPersonaCdaItem[] Persona, ref int Paccednum, ref sbyte Pacvernum) {
            object[] results = this.Invoke("Execute", new object[] {
                        Persona,
                        Paccednum,
                        Pacvernum});
            Persona = ((DatPersonaCdaDatPersonaCdaItem[])(results[0]));
            Paccednum = ((int)(results[1]));
            Pacvernum = ((sbyte)(results[2]));
        }
        
        /// <remarks/>
        public void ExecuteAsync(DatPersonaCdaDatPersonaCdaItem[] Persona, int Paccednum, sbyte Pacvernum) {
            this.ExecuteAsync(Persona, Paccednum, Pacvernum, null);
        }
        
        /// <remarks/>
        public void ExecuteAsync(DatPersonaCdaDatPersonaCdaItem[] Persona, int Paccednum, sbyte Pacvernum, object userState) {
            if ((this.ExecuteOperationCompleted == null)) {
                this.ExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExecuteOperationCompleted);
            }
            this.InvokeAsync("Execute", new object[] {
                        Persona,
                        Paccednum,
                        Pacvernum}, this.ExecuteOperationCompleted, userState);
        }
        
        private void OnExecuteOperationCompleted(object arg) {
            if ((this.ExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExecuteCompleted(this, new ExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="DatPersonaCda.DatPersonaCdaItem", Namespace="kb2")]
    public partial class DatPersonaCdaDatPersonaCdaItem {

        private string datPersonaCedNumField;

        private string datPersonaVerNumField;

        private string datPersonaRazCodField;
        
        private string datPersonaPrimerNombreField;
        
        private string datPersonaSegundoNombreField;
        
        private string datPersonaPrimerApellidoField;
        
        private string datPersonaSegundoApellidoField;

        private string datPersonaFchNacField;
        
        private string datPersonaSexoField;
        
        private string datPersonaRazaField;
        
        private string datPersonaNacionField;

        private string datPersonaRegNumField;
        
        private string datPersonaTelefonoField;
        
        private string datPersonaDomicilioField;
        
        private string datPersonalLocalidadField;
        
        private string datPersonaDeptoField;
        
        /// <remarks/>
        public string DatPersonaCedNum
        {
            get {
                return this.datPersonaCedNumField;
            }
            set {
                this.datPersonaCedNumField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaVerNum
        {
            get {
                return this.datPersonaVerNumField;
            }
            set {
                this.datPersonaVerNumField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaRazCod
        {
            get {
                return this.datPersonaRazCodField;
            }
            set {
                this.datPersonaRazCodField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaPrimerNombre {
            get {
                return this.datPersonaPrimerNombreField;
            }
            set {
                this.datPersonaPrimerNombreField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaSegundoNombre {
            get {
                return this.datPersonaSegundoNombreField;
            }
            set {
                this.datPersonaSegundoNombreField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaPrimerApellido {
            get {
                return this.datPersonaPrimerApellidoField;
            }
            set {
                this.datPersonaPrimerApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaSegundoApellido {
            get {
                return this.datPersonaSegundoApellidoField;
            }
            set {
                this.datPersonaSegundoApellidoField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaFchNac
        {
            get {
                return this.datPersonaFchNacField;
            }
            set {
                this.datPersonaFchNacField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaSexo {
            get {
                return this.datPersonaSexoField;
            }
            set {
                this.datPersonaSexoField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaRaza {
            get {
                return this.datPersonaRazaField;
            }
            set {
                this.datPersonaRazaField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaNacion {
            get {
                return this.datPersonaNacionField;
            }
            set {
                this.datPersonaNacionField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaRegNum
        {
            get {
                return this.datPersonaRegNumField;
            }
            set {
                this.datPersonaRegNumField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaTelefono {
            get {
                return this.datPersonaTelefonoField;
            }
            set {
                this.datPersonaTelefonoField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaDomicilio {
            get {
                return this.datPersonaDomicilioField;
            }
            set {
                this.datPersonaDomicilioField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonalLocalidad {
            get {
                return this.datPersonalLocalidadField;
            }
            set {
                this.datPersonalLocalidadField = value;
            }
        }
        
        /// <remarks/>
        public string DatPersonaDepto {
            get {
                return this.datPersonaDeptoField;
            }
            set {
                this.datPersonaDeptoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ExecuteCompletedEventHandler(object sender, ExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DatPersonaCdaDatPersonaCdaItem[] Persona {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DatPersonaCdaDatPersonaCdaItem[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Paccednum {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public sbyte Pacvernum {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sbyte)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591