//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("patient_info_dbModel", "fk_emergency_contact_Patient", "patient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataAccess.patient), "emergency_contact", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataAccess.emergency_contact), true)]

#endregion

namespace DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class patient_info_dbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new patient_info_dbEntities object using the connection string found in the 'patient_info_dbEntities' section of the application configuration file.
        /// </summary>
        public patient_info_dbEntities() : base("name=patient_info_dbEntities", "patient_info_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new patient_info_dbEntities object.
        /// </summary>
        public patient_info_dbEntities(string connectionString) : base(connectionString, "patient_info_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new patient_info_dbEntities object.
        /// </summary>
        public patient_info_dbEntities(EntityConnection connection) : base(connection, "patient_info_dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<emergency_contact> emergency_contact
        {
            get
            {
                if ((_emergency_contact == null))
                {
                    _emergency_contact = base.CreateObjectSet<emergency_contact>("emergency_contact");
                }
                return _emergency_contact;
            }
        }
        private ObjectSet<emergency_contact> _emergency_contact;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<patient> patient
        {
            get
            {
                if ((_patient == null))
                {
                    _patient = base.CreateObjectSet<patient>("patient");
                }
                return _patient;
            }
        }
        private ObjectSet<patient> _patient;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the emergency_contact EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemergency_contact(emergency_contact emergency_contact)
        {
            base.AddObject("emergency_contact", emergency_contact);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the patient EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopatient(patient patient)
        {
            base.AddObject("patient", patient);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="patient_info_dbModel", Name="emergency_contact")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class emergency_contact : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new emergency_contact object.
        /// </summary>
        /// <param name="idemergency_contact">Initial value of the idemergency_contact property.</param>
        /// <param name="patient_idPatient">Initial value of the Patient_idPatient property.</param>
        public static emergency_contact Createemergency_contact(global::System.Int32 idemergency_contact, global::System.Int32 patient_idPatient)
        {
            emergency_contact emergency_contact = new emergency_contact();
            emergency_contact.idemergency_contact = idemergency_contact;
            emergency_contact.Patient_idPatient = patient_idPatient;
            return emergency_contact;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idemergency_contact
        {
            get
            {
                return _idemergency_contact;
            }
            set
            {
                if (_idemergency_contact != value)
                {
                    Onidemergency_contactChanging(value);
                    ReportPropertyChanging("idemergency_contact");
                    _idemergency_contact = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idemergency_contact");
                    Onidemergency_contactChanged();
                }
            }
        }
        private global::System.Int32 _idemergency_contact;
        partial void Onidemergency_contactChanging(global::System.Int32 value);
        partial void Onidemergency_contactChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Patient_idPatient
        {
            get
            {
                return _Patient_idPatient;
            }
            set
            {
                OnPatient_idPatientChanging(value);
                ReportPropertyChanging("Patient_idPatient");
                _Patient_idPatient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Patient_idPatient");
                OnPatient_idPatientChanged();
            }
        }
        private global::System.Int32 _Patient_idPatient;
        partial void OnPatient_idPatientChanging(global::System.Int32 value);
        partial void OnPatient_idPatientChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("patient_info_dbModel", "fk_emergency_contact_Patient", "patient")]
        public patient patient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<patient> patientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<patient>("patient_info_dbModel.fk_emergency_contact_Patient", "patient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="patient_info_dbModel", Name="patient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class patient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new patient object.
        /// </summary>
        /// <param name="idPatient">Initial value of the idPatient property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="surname">Initial value of the surname property.</param>
        /// <param name="document">Initial value of the document property.</param>
        public static patient Createpatient(global::System.Int32 idPatient, global::System.String name, global::System.String surname, global::System.String document)
        {
            patient patient = new patient();
            patient.idPatient = idPatient;
            patient.name = name;
            patient.surname = surname;
            patient.document = document;
            return patient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPatient
        {
            get
            {
                return _idPatient;
            }
            set
            {
                if (_idPatient != value)
                {
                    OnidPatientChanging(value);
                    ReportPropertyChanging("idPatient");
                    _idPatient = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idPatient");
                    OnidPatientChanged();
                }
            }
        }
        private global::System.Int32 _idPatient;
        partial void OnidPatientChanging(global::System.Int32 value);
        partial void OnidPatientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String document
        {
            get
            {
                return _document;
            }
            set
            {
                OndocumentChanging(value);
                ReportPropertyChanging("document");
                _document = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("document");
                OndocumentChanged();
            }
        }
        private global::System.String _document;
        partial void OndocumentChanging(global::System.String value);
        partial void OndocumentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telephone
        {
            get
            {
                return _telephone;
            }
            set
            {
                OntelephoneChanging(value);
                ReportPropertyChanging("telephone");
                _telephone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telephone");
                OntelephoneChanged();
            }
        }
        private global::System.String _telephone;
        partial void OntelephoneChanging(global::System.String value);
        partial void OntelephoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cell_phone
        {
            get
            {
                return _cell_phone;
            }
            set
            {
                Oncell_phoneChanging(value);
                ReportPropertyChanging("cell_phone");
                _cell_phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cell_phone");
                Oncell_phoneChanged();
            }
        }
        private global::System.String _cell_phone;
        partial void Oncell_phoneChanging(global::System.String value);
        partial void Oncell_phoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address
        {
            get
            {
                return _address;
            }
            set
            {
                OnaddressChanging(value);
                ReportPropertyChanging("address");
                _address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address");
                OnaddressChanged();
            }
        }
        private global::System.String _address;
        partial void OnaddressChanging(global::System.String value);
        partial void OnaddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String neighborhood
        {
            get
            {
                return _neighborhood;
            }
            set
            {
                OnneighborhoodChanging(value);
                ReportPropertyChanging("neighborhood");
                _neighborhood = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("neighborhood");
                OnneighborhoodChanged();
            }
        }
        private global::System.String _neighborhood;
        partial void OnneighborhoodChanging(global::System.String value);
        partial void OnneighborhoodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String e_mail
        {
            get
            {
                return _e_mail;
            }
            set
            {
                One_mailChanging(value);
                ReportPropertyChanging("e_mail");
                _e_mail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("e_mail");
                One_mailChanged();
            }
        }
        private global::System.String _e_mail;
        partial void One_mailChanging(global::System.String value);
        partial void One_mailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("patient_info_dbModel", "fk_emergency_contact_Patient", "emergency_contact")]
        public EntityCollection<emergency_contact> emergency_contact
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<emergency_contact>("patient_info_dbModel.fk_emergency_contact_Patient", "emergency_contact");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<emergency_contact>("patient_info_dbModel.fk_emergency_contact_Patient", "emergency_contact", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
